
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://tgfr6hqt82dk.share.zrok.io/#/'
          #rules_file_name: '.zap/rules.tsv'
          #cmd_options: '-a'
          #docker_name: 'owasp/zap2docker-stable'
          #rules_file_name: '.zap/rules.tsv'
          #cmd_options: 'a'
   
